modLoader="javafml"
loaderVersion="[${majorForgeVersion},)"
license="All rights reserved"
issueTrackerURL="https://github.com/ManasMods/CloudSettings/issues"
[[mods]]
    modId="cloudsettings"
    version="${version}"
    displayName="Cloud Settings"
    updateJSONURL="https://api.modrinth.com/updates/nnu4dJj4/forge_updates.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/cloudsettings"
    logoFile="icon.png"
    credits="Thanks for supporting me BisectHosting ♥"
    authors="MrProfessor"
    description='''
    A simple mod that synchronize your options.txt to other modpack instances
    '''
[[dependencies.cloudsettings]]
    modId="forge"
    mandatory=true
    versionRange="[${majorForgeVersion},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cloudsettings]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraftVersion},${nextMinecraftVersion})"
    ordering="NONE"
    side="BOTH"